version: '3.3'

services:
  webserver:
    build: docker/php
    restart: always
    ports:
      - '8123:80'
    volumes:
      - ./code:/var/www/html
  grunt:
    build: docker/node
    restart: always
    volumes:
      - ./code:/var/www/html
    command: grunt
    working_dir: /var/www/html
